### ISSUE TITLE
clip_qst, clip_word

### ISSUE THREAD

**Issue by haoyi-duan** [GeWu-Lab/PSTP-Net#2]
Hi, could you please tell me how do I get clip_qst features? I see clip_word[B, 77, C] can be extracted from extract_qst_clip_feat.py, but what about clip_qst[B, C]? Thank you!

**Comment by ayameyao** [comment]
Hi,
 
**file:** ./feat_script/extract_clip_feat/clip_net/model.py
Uncomment line 360, you can get qustion feat shape: [77, C]
Uncomment line 361, you can get qustion feat shape: [1, C]

**Comment by haoyi-duan** [comment]
Got it! Thank you so much!
